server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-db
    username: byte_cat
    password: byte_cat
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s